// resources/js/pages/guest/login.jsx
import { useForm } from '@inertiajs/inertia-react'
import Container from '@components/container'
import Form, { TextInput } from '@components/form'
import Button from '@components/button'

const Login = () => {
  const { data, setData, post, processing, errors } = useForm({
    username: '',
    password: '',
    remember: 0,
  })

  const handleTextChange = (e) => {
    const { name, value } = e.target
    switch (name) {
      case 'username':
      case 'password':
        setData(name, value)
        break
    }
  }

  return (
    <Container width="max-w-md flex flex-col">
      <h1 className="text-center py-14 text-2xl font-bold">
        Handwriting Comparator Ex
      </h1>
      <div className="flex">
        <Form
          legend="Login Form"
          className="m-auto"
          onSubmit={(_e) => {
            console.log(data)
          }}
        >
          <TextInput
            name="username"
            label="Username"
            type="text"
            id="username"
            value={data.username}
            onChange={handleTextChange}
          />
          <TextInput
            name="password"
            label="Password"
            type="password"
            id="password"
            value={data.password}
            onChange={handleTextChange}
          />

          <Button className="mt-4" type="submit">
            Submit
          </Button>
        </Form>
      </div>
    </Container>
  )
}
export default Login

// resources/js/Pages/Guest/Login.vue
<template>
    <div class="content">
        <div class="form-content">
            <n-form @submit.prevent="loginForm.post(route('post.login'))" :model="loginForm">
                <n-form-item label="Username" :required="true" path="username">
                    <n-input v-model:value="loginForm.username" />
                </n-form-item>
                <n-form-item label="Password" :required="true" path="password">
                    <n-input type="password" show-password-on="click" v-model:value="loginForm.password" />
                </n-form-item>
                <n-form-item>
                    <n-button type="primary" block attr-type="submit" :loading="loginForm.processing">Login</n-button>
                </n-form-item>
            </n-form>
        </div>
    </div>
</template>


<script>
import { useForm } from '@inertiajs/inertia-vue3';
import { NForm, NFormItem, NInput, NButton } from 'naive-ui'
import Layout from '@/Components/Layouts/BaseLayout.vue'

export default {
    layout: Layout,
    components: {
        NForm,
        NFormItem,
        NInput,
        NButton
    },
    setup() {
        const loginForm = useForm({
            username: '',
            password: '',
            remember: false,
        });

        return { loginForm }
    }
}
</script>

<style scoped>
.content {
    padding: 8rem;
    display: flex;
    justify-content: center;
}

.form-content {
    width: 100%;
    max-width: 320px;
}
</style>
