// resources/js/pages/auth/admin/create-user.jsx
import { Fragment, useEffect, useMemo } from 'react'
import { isArray, isString } from 'lodash'
import { useForm } from '@inertiajs/inertia-react'
import AdminLayout from '@components/layouts/admin'
import Head from '@components/head'
import Header from '@components/header'
import BackLink from '@components/back-link'
import Container from '@components/container'
import Button from '@components/button'
import Form, { Fieldset, TextInput, Select } from '@components/form'

const DetailFields = ({ data, setData }) => {
  if (data.role === 'admin') {
    return <></>
  }
  const roleStudent = data.role === 'student'
  const roleStudentOrInstructor =
    data.role === 'instructor' || data.role === 'student'

  const handleDetailsInput = (e) => {
    const { value, name } = e.target
    const details = {
      ...data.details,
      [name]: value,
    }
    setData('details', details)
  }

  return (
    <div className="flex flex-col gap-2">
      {roleStudentOrInstructor ? (
        <div className="md:flex md:gap-2">
          <TextInput
            name="contact"
            label="Contact Number"
            type="text"
            id="contact"
            className="grow"
            value={data.details.contact}
            onChange={(e) => handleDetailsInput(e)}
            maxLength={11}
          />

          <TextInput
            name="email"
            label="Email"
            type="email"
            id="email"
            className="grow"
            value={data.details.email}
            onChange={(e) => handleDetailsInput(e)}
          />
        </div>
      ) : (
        <></>
      )}
      {roleStudent ? (
        <div className="md:flex md:gap-2">
          <TextInput
            name="contactPerson"
            label="Contact Person"
            type="text"
            id="contactPerson"
            className="grow"
            value={data.details.contactPerson}
            onChange={(e) => handleDetailsInput(e)}
          />
          <TextInput
            name="contactPersonContact"
            label="Contact Number"
            type="text"
            id="contactPersonContact"
            className="grow"
            value={data.details.contactPersonContact}
            onChange={(e) => handleDetailsInput(e)}
          />
        </div>
      ) : (
        <></>
      )}
    </div>
  )
}

const CreateUser = ({ roles }) => {
  /** Validate args */
  if (import.meta.env.DEV) {
    useEffect(() => {
      ;(async () => {
        const joi = (await import('joi')).default
        joi.array().items(joi.string()).validate(roles)
      })().catch(console.error)
    }, [roles])
  }

  const { data, setData, post, processing, errors } = useForm({
    username: '',
    role: '',
    lName: '',
    mName: '',
    fName: '',
    details: {
      contact: '',
      email: '',
      contactPerson: '',
      contactPersonContact: '',
    },
  })

  const handleTextChange = (e) => {
    const { name, value } = e.target
    setData(name, value)
  }

  const roleOptions = roles.map((v) => ({
    label: `${v.charAt(0).toUpperCase()}${v.slice(1)}`,
    value: v,
  }))

  const detailsErrorMessage = useMemo(() => {
    return <></>
  }, [data.lName, data.details])

  return (
    <Fragment>
      <Head title="Create User" />

      <AdminLayout>
        <Header>
          <BackLink />
          <h1 className="text-xl font-bold">Create User</h1>
        </Header>

        <Container width="max-w-4xl" className="pt-4">
          <Form
            legend="Create User Form"
            onSubmit={(_) => {
              const target = route('post.admin.create_user')
              post(target)
            }}
            id="create-user-form"
          >
            <Fieldset legend="User Credentials" className="w-full">
              {detailsErrorMessage}

              <div className="flex flex-col md:flex-row gap-2">
                <TextInput
                  name="username"
                  label="Username"
                  type="text"
                  id="username"
                  value={data.username}
                  onChange={handleTextChange}
                  error={errors.username}
                  autoFocus
                />

                <Select
                  id="role"
                  label="Role"
                  form="create-user-form"
                  placeholder="Select a role"
                  className="md:w-fit"
                  options={roleOptions}
                  value={data.role}
                  onChange={(e) => setData('role', e.target.value)}
                  error={errors.role}
                />
              </div>
            </Fieldset>

            <Fieldset legend="User Details" isLegendVisible>
              <div className="flex flex-col gap-2">
                <div className="flex flex-col flex-wrap md:flex-row gap-2">
                  <TextInput
                    name="lName"
                    label="Last Name"
                    type="text"
                    id="lName"
                    className="grow"
                    value={data.lName}
                    onChange={handleTextChange}
                    error={errors.lName}
                  />

                  <TextInput
                    name="fName"
                    label="First Name"
                    type="text"
                    id="fName"
                    className="grow"
                    value={data.fName}
                    onChange={handleTextChange}
                    error={errors.fName}
                  />

                  <TextInput
                    name="mName"
                    label="Middle Name"
                    type="text"
                    id="mName"
                    className="grow md:grow-0 lg:grow"
                    value={data.mName}
                    onChange={handleTextChange}
                    error={errors.mName}
                  />
                </div>

                <DetailFields data={data} setData={setData} />
              </div>
            </Fieldset>

            <Button
              className="mt-4 ml-auto"
              disabled={processing}
              type="submit"
            >
              Submit
            </Button>
          </Form>
        </Container>
      </AdminLayout>
    </Fragment>
  )
}
export default CreateUser

// resources/js/Pages/Auth/Admin/CreateUser.vue
<template>
    <n-layout>
        <n-layout-header>
            <n-page-header title="Create User" @back="() => backLink()" style="overflow: hidden;" />
        </n-layout-header>
        <n-layout-content content-style="padding: 24px;">
            <n-form @submit.prevent="() => userForm.post(route('post.admin.create_user'))" label-placement="left"
                require-mark-placement="right-hanging" label-width="120" :model="userForm" style="max-width: 400px;">
                <n-form-item label="Username" path="username" required>
                    <n-input v-model:value="userForm.username" />
                </n-form-item>
                <n-form-item label="Role" path="role" required style="text-transform: capitalize;">
                    <n-select v-model:value="userForm.role" :options="roleOptions" />
                </n-form-item>
                <n-form-item label="Last Name" path="lName" required>
                    <n-input v-model:value="userForm.lName" />
                </n-form-item>
                <n-form-item label="Middle Name" path="mName">
                    <n-input v-model:value="userForm.mName" />
                </n-form-item>
                <n-form-item label="First Name" path="fName" required>
                    <n-input v-model:value="userForm.fName" />
                </n-form-item>

                <!-- HACK: Manually setting if guards for roles -->
                <n-form-item v-if="userForm.role === 'instructor' || userForm.role === 'student'" label="Contact"
                    path="details.contact" required>
                    <n-input-number v-model:value="userForm.details.contact" :show-button="false"
                        style="width: 100%;" />
                </n-form-item>
                <n-form-item v-if="userForm.role === 'instructor' || userForm.role === 'student'" label="Email"
                    path="details.email" required>
                    <n-input v-model:value="userForm.details.email" />
                </n-form-item>
                <n-form-item v-if="userForm.role === 'student'" label="Contact Person" path="details.contactPerson">
                    <n-input v-model:value="userForm.details.contactPerson" />
                </n-form-item>
                <n-form-item v-if="userForm.role === 'student'" label="Contact Person Mobile"
                    path="details.contactPersonContact">
                    <n-input-number v-model:value="userForm.details.contactPersonContact" :show-button="false"
                        style="width: 100%;" />
                </n-form-item>
                <n-form-item>
                    <n-button type="primary" attr-type="submit" :loading="userForm.processing" :style="{
                        marginRight: 0,
                        marginLeft: 'auto'
                    }">Submit</n-button>
                </n-form-item>
            </n-form>
        </n-layout-content>
    </n-layout>
</template>

<script>
import { Inertia } from '@inertiajs/inertia'
import {
    NLayout,
    NLayoutContent,
    NLayoutHeader,
    NH2,
    NButton,
    NPageHeader,
    NForm,
    NFormItem,
    NInput,
    NInputNumber,
    NSelect,
} from 'naive-ui'
import { useForm } from '@inertiajs/inertia-vue3'
import Layout from '@/Components/Layouts/AdminLayout.vue'

export default {
    layout: Layout,
    components: {
        NLayout,
        NLayoutContent,
        NLayoutHeader,
        NH2,
        NButton,
        NPageHeader,
        NForm,
        NFormItem,
        NInput,
        NInputNumber,
        NSelect,
    },
    props: {
        roles: Array
    },
    setup(props) {
        const roleOptions = props.roles.map((value) => ({
            label: value,
            value
        }))

        const userForm = useForm({
            username: '',
            role: '',
            lName: '',
            mName: '',
            fName: '',
            details: {
                contact: 9,
                email: '',
                contactPerson: '',
                contactPersonContact: 9,
            },
        })

        function backLink() {
            Inertia.get(route('admin.index'))
        }

        return {
            userForm,
            backLink,
            roleOptions
        }
    }
}
</script>
